Config = {}

Config.Locations = {
   ["duty"] = {
       [1] = vector3(1768.39, 3322.72, 41.44),
   },
   ["vehicle"] = {
       [1] = vector4(1733.04, 3303.61, 41.22, 193.32),
   },
   ["stash"] = {
       [1] = vector3(1765.55, 3321.23, 41.44),
   },
   ["parts"] = {
	   [1] = vector3(1757.98, 3334.89, 41.26),
   },
   ["stations"] = {
       [1] = {label = "Blue Line Towing and Repairs", coords = vector4(1774.35, 3323.66, 41.43, 312.69)},
   },
}

Config.AuthorizedVehicles = {
	-- Grade 0
	[0] = {
		["flatbed3"] = "Flatbed",
		["bc205500w"] = "Ford Ram 5500",
		["ct660tow"] = "CAT Tow",
        ["f150ex"] = "Ford F150 Utility",
	},
	-- Grade 1
	[1] = {
		["flatbed3"] = "Flatbed",
		["bc205500w"] = "Ford Ram 5500",
		["ct660tow"] = "CAT Tow",
        ["f150ex"] = "Ford F150 Utility",
	},
	-- Grade 2
	[2] = {
		["flatbed3"] = "Flatbed",
		["bc205500w"] = "Ford Ram 5500",
		["ct660tow"] = "CAT Tow",
        ["f150ex"] = "Ford F150 Utility",
	},
	-- Grade 3
	[3] = {
		["flatbed3"] = "Flatbed",
		["bc205500w"] = "Ford Ram 5500",
		["ct660tow"] = "CAT Tow",
        ["f150ex"] = "Ford F150 Utility",
	},
	-- Grade 4
	[4] = {
		["flatbed3"] = "Flatbed",
		["bc205500w"] = "Ford Ram 5500",
		["ct660tow"] = "CAT Tow",
        ["f150ex"] = "Ford F150 Utility",
	},
    [5] = {
		["flatbed3"] = "Flatbed",
		["bc205500w"] = "Ford Ram 5500",
		["ct660tow"] = "CAT Tow",
        ["f150ex"] = "Ford F150 Utility",
	},
}

Config.Items = {
    label = "Car Parts",
    slots = 30,
    items = {
        [1] = {
            name = "mechanic_tools",
            price = 0,
            amount = 150,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "toolbox",
            price = 0,
            amount = 150,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "turbo",
            price = 0,
            amount = 150,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "v8engine",
            price = 0,
            amount = 150,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "shonen",
            price = 0,
            amount = 150,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "race_transmission",
            price = 0,
            amount = 150,
            info = {},
            type = "item",
            slot = 6,
        },
		[7] = {
            name = "race_brakes",
            price = 0,
            amount = 150,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "suspension",
            price = 0,
            amount = 150,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "suspension2",
            price = 0,
            amount = 150,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "nos",
            price = 0,
            amount = 150,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "underglow_controller",
            price = 0,
            amount = 150,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "headlights",
            price = 0,
            amount = 150,
            info = {},
            type = "item",
            slot = 12,
        },
		[13] = {
            name = "tint_supplies",
            price = 0,
            amount = 150,
            info = {},
            type = "item",
            slot = 13,
        },
        [14] = {
            name = "customplate",
            price = 0,
            amount = 150,
            info = {},
            type = "item",
            slot = 14,
        },
        [15] = {
            name = "hood",
            price = 0,
            amount = 150,
            info = {},
            type = "item",
            slot = 15,
        },
        [16] = {
            name = "roof",
            price = 0,
            amount = 150,
            info = {},
            type = "item",
            slot = 16,
        },
        [17] = {
            name = "spoiler",
            price = 0,
            amount = 150,
            info = {},
            type = "item",
            slot = 17,
        },
        [18] = {
            name = "bumper",
            price = 0,
            amount = 150,
            info = {},
            type = "item",
            slot = 18,
        },
		[19] = {
            name = "skirts",
            price = 0,
            amount = 150,
            info = {},
            type = "item",
            slot = 19,
        },
        [20] = {
            name = "exhaust",
            price = 0,
            amount = 150,
            info = {},
            type = "item",
            slot = 20,
        },
        [21] = {
            name = "seat",
            price = 0,
            amount = 150,
            info = {},
            type = "item",
            slot = 21,
        },
        [22] = {
            name = "rims",
            price = 0,
            amount = 150,
            info = {},
            type = "item",
            slot = 22,
        },
        [23] = {
            name = "livery",
            price = 0,
            amount = 150,
            info = {},
            type = "item",
            slot = 23,
        },
        [24] = {
            name = "paintcan",
            price = 0,
            amount = 150,
            info = {},
            type = "item",
            slot = 24,
        },
		[25] = {
            name = "tires",
            price = 0,
            amount = 150,
            info = {},
            type = "item",
            slot = 25,
        },
        [26] = {
            name = "horn",
            price = 0,
            amount = 150,
            info = {},
            type = "item",
            slot = 26,
        },
        [27] = {
            name = "internals",
            price = 0,
            amount = 150,
            info = {},
            type = "item",
            slot = 27,
        },
        [28] = {
            name = "externals",
            price = 0,
            amount = 150,
            info = {},
            type = "item",
            slot = 28,
        }
    }
}